-- 이렇게 ddl.sql을 따로 저장하고 있어야 관리가 편하다

-- 테이블 생성 sql
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

-- member 추가 sql
insert into member(name) values('Spring');
insert into member(name) values('Spring2');